// scaffold.js — genera la estructura completa del sitio BBAnime.
// v4: scroll-scrubbing real (estilo pagina de producto de Apple). La botella ya
// no gira sola en loop autonomo: el frame que se dibuja en <canvas> depende
// exactamente de la posicion de scroll del usuario (se congela si para de
// scrollear). Los 181 frames reales viven en assets/frames/ (extraidos del
// video del cliente con ffmpeg). Ejecutar con: node scaffold.js
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const FRAME_COUNT = 181;

function write(relPath, lines) {
  const full = path.join(ROOT, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, lines.join('\n'), 'utf8');
  console.log('  creado:', relPath);
}

// ---------------------------------------------------------------------------
// Sparkles (estrellas) — set fijo de posiciones/colores
// ---------------------------------------------------------------------------
function buildSparkles() {
  var positions = [
    { x: '8%', y: '18%', c: 'pink', s: 22 },
    { x: '88%', y: '12%', c: 'cyan', s: 16 },
    { x: '15%', y: '72%', c: 'gold', s: 18 },
    { x: '92%', y: '68%', c: 'pink', s: 14 },
    { x: '48%', y: '8%', c: 'cyan', s: 12 },
    { x: '6%', y: '46%', c: 'gold', s: 12 },
    { x: '95%', y: '40%', c: 'pink', s: 18 },
    { x: '30%', y: '88%', c: 'cyan', s: 14 },
    { x: '70%', y: '90%', c: 'gold', s: 16 }
  ];
  var out = [];
  positions.forEach(function (p, i) {
    out.push(
      '    <svg class="spark spark-' + p.c + '" style="left:' + p.x + '; top:' + p.y +
      '; width:' + p.s + 'px; height:' + p.s + 'px; animation-delay:' + (i * 0.35) + 's;" ' +
      'viewBox="0 0 24 24" aria-hidden="true"><path d="M12 0 L14.5 9.5 L24 12 L14.5 14.5 L12 24 L9.5 14.5 L0 12 L9.5 9.5 Z"/></svg>'
    );
  });
  return out.join('\n');
}

// ---------------------------------------------------------------------------
// Placeholder de emergencia (solo se ve si los frames reales no cargan).
// ---------------------------------------------------------------------------
function buildBottlePlaceholder() {
  return [
    '        <div class="bottle-glow" aria-hidden="true"></div>',
    '        <div class="bottle-inner" aria-hidden="true">',
    '          <div class="bottle-cap"></div>',
    '          <div class="bottle-body">',
    '            <div class="bottle-band"></div>',
    '          </div>',
    '        </div>',
    '        <div class="accessory accessory-hat" aria-hidden="true"></div>',
    '        <div class="accessory accessory-vest" aria-hidden="true"></div>',
    '        <div class="accessory accessory-scarf" aria-hidden="true"></div>'
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Iconos de stats (simples, inline)
// ---------------------------------------------------------------------------
function iconDroplet() {
  return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 C12 2 5 11 5 15.5 A7 7 0 0 0 19 15.5 C19 11 12 2 12 2 Z"/></svg>';
}
function iconBottle() {
  return '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="2" width="6" height="4" rx="1.2"/><path d="M8 7 h8 l1.4 3.2 v10.3 a1.5 1.5 0 0 1 -1.5 1.5 h-7.8 a1.5 1.5 0 0 1 -1.5 -1.5 v-10.3 z"/></svg>';
}

// ---------------------------------------------------------------------------
// index.html
// ---------------------------------------------------------------------------
function buildIndexHtml() {
  return [
    '<!DOCTYPE html>',
    '<html lang="es-AR">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>BBAnime | Botellas Termo Personalizadas de Anime Impresas en 3D</title>',
    '  <meta name="description" content="Botellas termicas personalizadas con tu personaje de anime favorito, impresas en 3D. Vos elegis el universo, nosotros lo dibujamos.">',
    '  <meta name="robots" content="index, follow">',
    '  <link rel="canonical" href="https://bbanime.vercel.app/">',
    '',
    '  <meta property="og:type" content="website">',
    '  <meta property="og:title" content="BBAnime | Botellas Termo Personalizadas de Anime">',
    '  <meta property="og:description" content="Tu personaje de anime favorito, impreso en 3D sobre una botella termica real. Shonen, mecha, slice of life: vos elegis el universo.">',
    '  <meta property="og:image" content="https://bbanime.vercel.app/assets/img/og-image.jpg">',
    '  <meta property="og:url" content="https://bbanime.vercel.app/">',
    '  <meta property="og:locale" content="es_AR">',
    '',
    '  <meta name="twitter:card" content="summary_large_image">',
    '  <meta name="twitter:title" content="BBAnime | Botellas Termo Personalizadas de Anime">',
    '  <meta name="twitter:description" content="Tu personaje de anime favorito, impreso en 3D sobre una botella termica real.">',
    '  <meta name="twitter:image" content="https://bbanime.vercel.app/assets/img/og-image.jpg">',
    '',
    '  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 32 32%22%3E%3Crect width=%2232%22 height=%2232%22 rx=%2210%22 fill=%22%230B0A1F%22/%3E%3Ctext x=%2216%22 y=%2222%22 font-size=%2216%22 text-anchor=%22middle%22 fill=%22%23FF3D8F%22 font-family=%22sans-serif%22%3EB%3C/text%3E%3C/svg%3E">',
    '',
    '  <link rel="preconnect" href="https://fonts.googleapis.com">',
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '  <link href="https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=Inter:wght@400;500;600;700;800&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">',
    '',
    '  <link rel="stylesheet" href="css/style.css">',
    '',
    '  <script type="application/ld+json">',
    '  {',
    '    "@context": "https://schema.org",',
    '    "@type": "OnlineStore",',
    '    "name": "BBAnime",',
    '    "url": "https://bbanime.vercel.app/",',
    '    "description": "Botellas termicas personalizadas de anime, impresas en 3D.",',
    '    "areaServed": "AR",',
    '    "sameAs": ["https://www.instagram.com/bbanime", "https://www.tiktok.com/@bbanime"]',
    '  }',
    '  </script>',
    '</head>',
    '<body>',
    '',
    '  <div id="loader">',
    '    <div class="loader-brand">Bbanime</div>',
    '    <div id="loader-bar"><div id="loader-bar-fill"></div></div>',
    '    <div id="loader-percent">0%</div>',
    '  </div>',
    '',
    '  <div class="bg-scene" aria-hidden="true">',
    '    <div class="bg-cosmic"></div>',
    buildSparkles(),
    '    <canvas id="canvas"></canvas>',
    '    <div class="bottle-stage" id="bottle-placeholder">',
    buildBottlePlaceholder(),
    '    </div>',
    '  </div>',
    '',
    '  <header class="site-header" id="site-header">',
    '    <nav class="site-nav">',
    '      <a href="#top" class="logo">Bb<span>anime</span></a>',
    '      <button class="nav-toggle" id="nav-toggle" aria-label="Abrir menu" aria-expanded="false">',
    '        <span></span><span></span><span></span>',
    '      </button>',
    '      <ul class="nav-links" id="nav-links">',
    '        <li><a href="#que-hacemos">Qué hacemos</a></li>',
    '        <li><a href="#universo">Tu universo</a></li>',
    '        <li><a href="#proceso">Proceso</a></li>',
    '        <!-- TODO: reemplazar por la URL real de la tienda externa -->',
    '        <li><a href="https://tu-tienda-externa.com" class="nav-cta" target="_blank" rel="noopener">Tienda <i>&#8599;</i></a></li>',
    '      </ul>',
    '    </nav>',
    '  </header>',
    '',
    '  <main id="top">',
    '',
    '    <section class="phase phase-hero" id="hero">',
    '      <div class="phase-copy">',
    '        <span class="section-label">000 / BBANIME</span>',
    '        <h1 class="hero-logo">Bb<span>anime</span></h1>',
    '        <p class="hero-tagline">Botellas termo de anime, hechas para ti.</p>',
    '        <div class="scroll-indicator"><span>Scroll</span><i>&#8595;</i></div>',
    '      </div>',
    '    </section>',
    '',
    '    <section class="phase" id="que-hacemos">',
    '      <div class="phase-copy">',
    '        <span class="section-label">001 / Qué hacemos</span>',
    '        <h2 class="section-heading">Tu personaje, en una botella real</h2>',
    '        <p class="section-body">Nos mandás el diseño de tu personaje favorito y lo llevamos a una botella térmica real, impresa en 3D pieza por pieza. Cada botella es una edición única, como el personaje que elegiste.</p>',
    '      </div>',
    '    </section>',
    '',
    '    <section class="phase phase-right" id="universo">',
    '      <div class="phase-copy">',
    '        <span class="section-label">002 / Tu universo</span>',
    '        <h2 class="section-heading">Chicas mágicas, isekai, mechas, anime.</h2>',
    '        <p class="section-body">Si existe en tu universo favorito, lo llevamos a tu botella.</p>',
    '      </div>',
    '    </section>',
    '',
    '    <section class="phase phase-list" id="proceso">',
    '      <div class="phase-copy phase-copy-wide">',
    '        <span class="section-label center">003 / Proceso</span>',
    '        <h2 class="section-heading center">Cómo la hacemos</h2>',
    '        <div class="process-list">',
    '          <div class="process-item">',
    '            <span class="process-number">01</span>',
    '            <h3>Elegí tu personaje</h3>',
    '            <p>Nos mandás tu ilustración o elegís una de nuestra galería con licencia de artistas.</p>',
    '          </div>',
    '          <div class="process-item">',
    '            <span class="process-number">02</span>',
    '            <h3>Diseño 3D</h3>',
    '            <p>Modelamos el relieve sobre el molde de la botella y te mostramos una previa antes de imprimir.</p>',
    '          </div>',
    '          <div class="process-item">',
    '            <span class="process-number">03</span>',
    '            <h3>Impresión 3D</h3>',
    '            <p>Imprimimos capa por capa en PLA+ apto alimentario, con el detalle de tu personaje en relieve.</p>',
    '          </div>',
    '          <div class="process-item">',
    '            <span class="process-number">04</span>',
    '            <h3>Pintado y sellado</h3>',
    '            <p>Pintamos a mano y sellamos con doble pared térmica, lista para viajar con vos.</p>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </section>',
    '',
    '    <section class="phase phase-list" id="datos">',
    '      <div class="phase-copy phase-copy-wide">',
    '        <span class="section-label center">004 / BBAnime en datos</span>',
    '        <div class="stats-list">',
    '          <div class="stat">',
    '            <span class="stat-icon">' + iconDroplet() + '</span>',
    '            <span class="stat-number" data-value="12" data-decimals="0">0</span><span class="stat-suffix">h</span>',
    '            <span class="stat-label">Retención de frío</span>',
    '          </div>',
    '          <div class="stat">',
    '            <span class="stat-icon">' + iconBottle() + '</span>',
    '            <span class="stat-number" data-value="500" data-decimals="0">0</span><span class="stat-suffix">ml</span>',
    '            <span class="stat-label">Capacidad</span>',
    '          </div>',
    '          <div class="stat">',
    '            <span class="stat-icon stat-icon-infinity">&#8734;</span>',
    '            <span class="stat-number-static">&#8734;</span>',
    '            <span class="stat-label">Animes posibles</span>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </section>',
    '',
    '    <section class="phase" id="tienda" data-persist="true">',
    '      <div class="phase-copy">',
    '        <span class="section-label center">005 / Tu botella</span>',
    '        <h2 class="section-heading center">Una botella. Tu anime. Para siempre.</h2>',
    '        <p class="section-body center">Elegís tu personaje, nosotros la imprimimos. Envíos a todo el país.</p>',
    '        <!-- TODO: reemplazar por la URL real de la tienda externa -->',
    '        <a href="https://tu-tienda-externa.com" class="cta-button" target="_blank" rel="noopener">Ver tienda <i>&#8599;</i></a>',
    '      </div>',
    '    </section>',
    '  </main>',
    '',
    '  <footer class="site-footer">',
    '    <div class="footer-inner">',
    '      <span class="logo">Bb<span>anime</span></span>',
    '      <ul class="footer-links">',
    '        <li><a href="https://www.instagram.com/bbanime" target="_blank" rel="noopener">Instagram</a></li>',
    '        <li><a href="https://www.tiktok.com/@bbanime" target="_blank" rel="noopener">TikTok</a></li>',
    '        <li><a href="mailto:hola@bbanime.com">hola@bbanime.com</a></li>',
    '      </ul>',
    '      <span class="footer-copy">&copy; 2026 BBAnime. Todos los derechos reservados. · Hecho por <a href="https://growestudio.online" target="_blank" rel="noopener">Growestudio.online</a></span>',
    '    </div>',
    '  </footer>',
    '',
    '  <script src="https://cdn.jsdelivr.net/npm/lenis@1/dist/lenis.min.js"></script>',
    '  <script src="https://cdn.jsdelivr.net/npm/gsap@3/dist/gsap.min.js"></script>',
    '  <script src="https://cdn.jsdelivr.net/npm/gsap@3/dist/ScrollTrigger.min.js"></script>',
    '  <script src="js/app.js"></script>',
    '</body>',
    '</html>',
    ''
  ].join('\n');
}

// ---------------------------------------------------------------------------
// css/style.css
// ---------------------------------------------------------------------------
function buildStyleCss() {
  return [
    '/* BBAnime — scroll-scrubbing real: el <canvas> de fondo dibuja el frame que */',
    '/* corresponde a la posicion de scroll (estilo pagina de producto de Apple). */',
    '/* Los textos bubble pasan por encima con el scroll, sin tarjetas. */',
    '',
    ':root {',
    '  --void: #1A1033;',
    '  --nebula: #241245;',
    '  --nebula-2: #2A1A55;',
    '  --bubble-pink: #FF199A;',
    '  --starlight: #FFFFFF;',
    '  --muted: #D6B8FF;',
    '  --bubble-glow: 62, 22, 130;',
    '  --cyan: #1FE0FF;',
    '  --gold: #FFDD00;',
    '  --font-display: "Bagel Fat One", system-ui, sans-serif;',
    '  --font-body: "Inter", system-ui, sans-serif;',
    '  --font-mono: "Space Mono", monospace;',
    '  --copy-shadow: 0 2px 20px rgba(0,0,0,0.5), 0 1px 8px rgba(0,0,0,0.6);',
    '}',
    '',
    '* { box-sizing: border-box; }',
    'html { scroll-behavior: smooth; overflow-x: hidden; }',
    'body {',
    '  margin: 0;',
    '  background: var(--void);',
    '  color: var(--starlight);',
    '  font-family: var(--font-body);',
    '  overflow-x: hidden;',
    '  position: relative;',
    '}',
    'img, svg { max-width: 100%; display: block; }',
    'a { color: inherit; text-decoration: none; }',
    'ul { list-style: none; margin: 0; padding: 0; }',
    '',
    '/* ---- Fondo fijo: cielo cosmico + canvas con scroll-scrubbing ------------ */',
    '.bg-scene { position: fixed; inset: 0; z-index: 0; overflow: hidden; }',
    '.bg-cosmic {',
    '  position: absolute; inset: 0;',
    '  background:',
    '    radial-gradient(ellipse at top right, rgba(255,61,165,0.25), transparent 50%),',
    '    radial-gradient(ellipse at bottom left, rgba(61,217,247,0.2), transparent 50%),',
    '    var(--void);',
    '}',
    '',
    '.spark { position: absolute; animation: twinkle 3.2s ease-in-out infinite; z-index: 1; }',
    '.spark-pink path { fill: var(--bubble-pink); }',
    '.spark-cyan path { fill: var(--cyan); }',
    '.spark-gold path { fill: var(--gold); }',
    '@keyframes twinkle { 0%, 100% { opacity: 0.25; transform: scale(0.8) rotate(0deg); } 50% { opacity: 1; transform: scale(1.1) rotate(15deg); } }',
    '',
    '#canvas { position: absolute; inset: 0; width: 100%; height: 100%; z-index: 2; }',
    '',
    '/* ---- Placeholder de emergencia (solo si los frames no llegan a cargar) -- */',
    '.bottle-stage {',
    '  position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%); z-index: 1;',
    '  width: min(64vmin, 560px); height: min(64vmin, 560px); perspective: 1000px; display: none;',
    '}',
    '.bottle-stage.visible { display: block; }',
    '.bottle-glow {',
    '  position: absolute; inset: -12%; border-radius: 50%;',
    '  background: radial-gradient(circle, var(--nebula-2) 0%, transparent 70%);',
    '}',
    '.bottle-inner {',
    '  position: absolute; left: 50%; top: 54%; transform-style: preserve-3d;',
    '  animation: spin-y 7s linear infinite;',
    '}',
    '@keyframes spin-y { from { transform: translate(-50%, -50%) rotateY(0deg); } to { transform: translate(-50%, -50%) rotateY(360deg); } }',
    '.bottle-cap { width: 15%; aspect-ratio: 2.2 / 1; margin: 0 auto; background: var(--bubble-pink); border-radius: 22% 22% 6% 6%; opacity: 0.92; }',
    '.bottle-body { width: 27%; aspect-ratio: 1 / 1.85; margin: -1% auto 0; background: #E9E6F5; border-radius: 30%; position: relative; }',
    '.bottle-band { position: absolute; left: 10%; right: 10%; top: 42%; height: 18%; background: var(--gold); opacity: 0.88; border-radius: 6%; }',
    '.accessory { position: absolute; left: 50%; top: 54%; }',
    '.accessory-hat { width: 20%; aspect-ratio: 2.6 / 1; margin-left: -10%; margin-top: -46%; background: var(--gold); border-radius: 50% 50% 20% 20%; animation: hat-cycle 9s ease-in-out infinite; }',
    '.accessory-vest { width: 16%; aspect-ratio: 1 / 1.3; margin-left: -8%; margin-top: -18%; background: var(--bubble-pink); opacity: 0.85; border-radius: 18%; animation: vest-cycle 9s ease-in-out infinite; }',
    '.accessory-scarf { width: 12%; aspect-ratio: 1 / 1.6; margin-left: -6%; margin-top: -6%; background: var(--cyan); opacity: 0.85; border-radius: 40%; animation: scarf-cycle 9s ease-in-out infinite; }',
    '@keyframes hat-cycle {',
    '  0%, 12% { transform: translate(-50%, -50%) translateY(0) rotate(0deg); opacity: 0.95; }',
    '  50% { transform: translate(-50%, -50%) translateY(-132px) rotate(-20deg); opacity: 0.15; }',
    '  88%, 100% { transform: translate(-50%, -50%) translateY(0) rotate(0deg); opacity: 0.95; }',
    '}',
    '@keyframes vest-cycle {',
    '  0%, 12% { transform: translate(-50%, -50%) translate(0, 0) rotate(0deg); opacity: 0.85; }',
    '  50% { transform: translate(-50%, -50%) translate(-122px, 34px) rotate(-28deg); opacity: 0.14; }',
    '  88%, 100% { transform: translate(-50%, -50%) translate(0, 0) rotate(0deg); opacity: 0.85; }',
    '}',
    '@keyframes scarf-cycle {',
    '  0%, 12% { transform: translate(-50%, -50%) translate(0, 0) rotate(0deg); opacity: 0.85; }',
    '  50% { transform: translate(-50%, -50%) translate(126px, 44px) rotate(24deg); opacity: 0.14; }',
    '  88%, 100% { transform: translate(-50%, -50%) translate(0, 0) rotate(0deg); opacity: 0.85; }',
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  *, *::before, *::after { animation-duration: 0.001ms !important; transition-duration: 0.001ms !important; }',
    '  .bottle-inner, .accessory, .spark { animation: none !important; }',
    '}',
    '',
    '/* ---- Loader ---------------------------------------------------------- */',
    '#loader {',
    '  position: fixed; inset: 0; z-index: 999; background: var(--void);',
    '  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 1rem;',
    '  transition: opacity 0.6s ease, visibility 0.6s ease;',
    '}',
    '#loader.hidden { opacity: 0; visibility: hidden; pointer-events: none; }',
    '.loader-brand { font-family: var(--font-display); font-weight: 700; color: var(--bubble-pink); font-size: 2rem; }',
    '#loader-bar { width: 220px; height: 6px; border-radius: 999px; background: rgba(245,241,255,0.12); overflow: hidden; }',
    '#loader-bar-fill { width: 0%; height: 100%; background: var(--cyan); transition: width 0.15s ease; }',
    '#loader-percent { font-family: var(--font-mono); color: var(--muted); font-size: 0.85rem; }',
    '',
    '/* ---- Header ------------------------------------------------------------ */',
    '.site-header {',
    '  position: fixed; top: 0; left: 0; right: 0; z-index: 100;',
    '  padding: 1.1rem 5vw;',
    '  transition: background 0.3s ease, backdrop-filter 0.3s ease, transform 0.4s ease, opacity 0.4s ease;',
    '}',
    '.site-header.scrolled { background: rgba(11, 10, 31, 0.4); backdrop-filter: blur(10px); }',
    '.site-header.hidden-nav { transform: translateY(-100%); opacity: 0; pointer-events: none; }',
    '.site-nav { display: flex; align-items: center; justify-content: space-between; }',
    '.logo { font-family: var(--font-display); font-weight: 700; font-size: 1.3rem; color: var(--bubble-pink); text-shadow: var(--copy-shadow); }',
    '.logo span { color: var(--starlight); }',
    '.nav-links {',
    '  position: fixed; inset: 0 0 0 26%; background: var(--nebula); border-left: 1px solid rgba(245,241,255,0.14);',
    '  display: flex; flex-direction: column; align-items: flex-start; justify-content: center; gap: 1.6rem;',
    '  padding: 2rem 8vw; transform: translateX(100%); transition: transform 0.4s ease; z-index: 90;',
    '}',
    '.nav-links.open { transform: translateX(0); }',
    '.nav-links a { font-family: var(--font-body); font-weight: 700; font-size: 1.1rem; }',
    '.nav-cta {',
    '  display: inline-flex; align-items: center; gap: 0.3rem; background: var(--bubble-pink); color: #fff;',
    '  padding: 0.5rem 1.1rem; border-radius: 999px; font-size: 0.85rem !important; font-weight: 800 !important;',
    '  text-shadow: none !important;',
    '}',
    '.nav-cta i { font-style: normal; }',
    '.nav-toggle {',
    '  z-index: 95; width: 40px; height: 32px; background: none; border: none; cursor: pointer;',
    '  display: flex; flex-direction: column; justify-content: space-between; padding: 4px 0;',
    '}',
    '.nav-toggle span { display: block; height: 3px; border-radius: 2px; background: var(--starlight); }',
    '',
    '@media (min-width: 768px) {',
    '  .nav-toggle { display: none; }',
    '  .nav-links {',
    '    position: static; inset: auto; background: none; border: none; flex-direction: row; align-items: center;',
    '    padding: 0; transform: none; gap: 2rem;',
    '  }',
    '  .nav-links a { font-size: 0.9rem; font-weight: 600; text-shadow: var(--copy-shadow); }',
    '}',
    '',
    '/* ---- Fases de contenido (scrollean sobre el fondo fijo) ---------------- */',
    'main { position: relative; z-index: 3; }',
    '.phase {',
    '  min-height: 82vh; display: flex; align-items: center; justify-content: center;',
    '  text-align: center; padding: 6rem 6vw; will-change: transform, opacity;',
    '}',
    '.phase-hero { min-height: 100vh; }',
    '.phase-hero .phase-copy::before { display: none; }',
    '.phase-right { justify-content: flex-end; text-align: right; }',
    '.phase-copy { position: relative; max-width: 30rem; text-shadow: var(--copy-shadow); z-index: 1; isolation: isolate; }',
    '.phase-copy::before {',
    '  content: ""; position: absolute; left: 50%; top: 50%; width: 108%; height: 118%;',
    '  transform: translate(-50%, -50%); z-index: -1; filter: blur(10px); pointer-events: none;',
    '  background: radial-gradient(ellipse at center,',
    '    rgba(var(--bubble-glow), 0.88) 0%,',
    '    rgba(var(--bubble-glow), 0.6) 40%,',
    '    rgba(var(--bubble-glow), 0) 72%);',
    '}',
    '.phase-copy-wide { max-width: 60rem; }',
    '.section-label {',
    '  font-family: var(--font-mono); color: var(--gold); font-size: 0.78rem; letter-spacing: 0.14em;',
    '  display: block; margin-bottom: 0.8rem;',
    '}',
    '.section-label.center { text-align: center; }',
    '.section-heading {',
    '  font-family: var(--font-display); font-weight: 700; font-size: clamp(1.8rem, 4.4vw, 3rem);',
    '  line-height: 1.12; margin: 0 0 1rem; color: var(--starlight); text-wrap: balance;',
    '}',
    '.section-heading.center { text-align: center; }',
    '.section-body { font-size: 1.08rem; line-height: 1.65; color: var(--muted); margin: 0; font-weight: 700; }',
    '.section-body.center { text-align: center; max-width: 32rem; margin: 0 auto; }',
    '',
    '.hero-logo {',
    '  font-family: var(--font-display); font-weight: 800; line-height: 1; margin: 0.7em 0 0.5em;',
    '  font-size: clamp(3.2rem, 14vw, 8rem); color: var(--bubble-pink); text-shadow: none;',
    '}',
    '.hero-logo span { color: var(--starlight); }',
    '.hero-tagline { font-size: clamp(1rem, 2vw, 1.3rem); color: #7C3AED; font-weight: 800; text-shadow: none; }',
    '.scroll-indicator { margin-top: 2rem; font-family: var(--font-mono); font-size: 0.78rem; color: var(--muted); display: flex; flex-direction: column; align-items: center; gap: 0.3rem; animation: bob 1.6s ease-in-out infinite; }',
    '@keyframes bob { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(8px); } }',
    '',
    '/* ---- Proceso (lista fluida, sin tarjetas) ------------------------------ */',
    '.process-list { display: grid; grid-template-columns: 1fr; gap: 1.6rem; margin-top: 2.2rem; text-align: left; }',
    '.process-number { font-family: var(--font-mono); color: var(--cyan); font-size: 1.4rem; display: block; margin-bottom: 0.4rem; }',
    '.process-item h3 { font-family: var(--font-display); font-weight: 700; font-size: 1.1rem; margin: 0 0 0.4rem; color: var(--starlight); }',
    '.process-item p { margin: 0; color: var(--muted); line-height: 1.5; font-weight: 600; font-size: 0.94rem; }',
    '@media (min-width: 700px) {',
    '  .process-list { grid-template-columns: repeat(4, 1fr); gap: 2rem; }',
    '  .process-item { border-left: 1px solid rgba(245,241,255,0.22); padding-left: 1.2rem; }',
    '  .process-item:first-child { border-left: none; padding-left: 0; }',
    '}',
    '',
    '/* ---- Stats (fila fluida, sin tarjetas) --------------------------------- */',
    '.stats-list { display: grid; grid-template-columns: 1fr; gap: 2rem; text-align: center; margin-top: 1.8rem; }',
    '.stat-icon { display: inline-flex; width: 42px; height: 42px; margin-bottom: 0.7rem; color: var(--cyan); filter: drop-shadow(0 2px 10px rgba(11,10,31,0.8)); }',
    '.stat-icon svg { width: 100%; height: 100%; fill: currentColor; }',
    '.stat-icon-infinity { font-size: 2rem; line-height: 1; color: var(--bubble-pink); font-family: var(--font-display); }',
    '.stat-number, .stat-number-static { font-family: var(--font-display); font-weight: 800; font-size: clamp(2.2rem, 5vw, 3.2rem); color: var(--starlight); font-variant-numeric: tabular-nums; }',
    '.stat-suffix { font-family: var(--font-display); font-weight: 800; font-size: clamp(1.3rem, 2.6vw, 1.8rem); color: var(--starlight); }',
    '.stat-label { display: block; font-family: var(--font-mono); font-size: 0.78rem; letter-spacing: 0.08em; margin-top: 0.5rem; color: var(--muted); }',
    '@media (min-width: 700px) {',
    '  .stats-list { grid-template-columns: repeat(3, 1fr); }',
    '  .stat { border-left: 1px solid rgba(245,241,255,0.22); }',
    '  .stat:first-child { border-left: none; }',
    '}',
    '',
    '/* ---- CTA ---------------------------------------------------------------- */',
    '.cta-button {',
    '  display: inline-flex; align-items: center; gap: 0.4rem; margin-top: 1.6rem; padding: 1rem 2.2rem;',
    '  background: var(--bubble-pink); color: #fff; font-family: var(--font-display); font-weight: 700;',
    '  border-radius: 999px; box-shadow: 0 6px 18px -6px rgba(255,25,154,0.5);',
    '  transition: transform 0.2s ease, box-shadow 0.2s ease; text-shadow: none;',
    '}',
    '.cta-button i { font-style: normal; }',
    '.cta-button:hover { transform: translateY(-3px); box-shadow: 0 0 0 1px rgba(255,61,143,0.5), 0 18px 36px -10px rgba(255,61,143,0.7); }',
    '',
    '/* ---- Footer --------------------------------------------------------------- */',
    '.site-footer { border-top: 1px solid rgba(245,241,255,0.14); background: var(--void); padding: 2.4rem 6vw; position: relative; z-index: 3; }',
    '.footer-inner { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 1rem; }',
    '.footer-links { display: flex; gap: 1.4rem; font-family: var(--font-mono); font-size: 0.85rem; color: var(--muted); }',
    '.footer-copy { font-family: var(--font-mono); font-size: 0.75rem; color: var(--muted); width: 100%; }',
    '@media (min-width: 700px) { .footer-copy { width: auto; } }',
    ''
  ].join('\n');
}

// ---------------------------------------------------------------------------
// js/app.js
// ---------------------------------------------------------------------------
function buildAppJs() {
  return [
    '// BBAnime — comportamiento del sitio (Lenis + GSAP ScrollTrigger)',
    '// Scroll-scrubbing real: el frame dibujado en <canvas> es una funcion directa',
    '// de la posicion de scroll dentro de <main> (0 = arriba del todo = botella',
    '// vestida, 1 = abajo del todo = botella vestida otra vez, con el desvestido',
    '// y el vestido en el medio). Si el usuario para de scrollear, el frame queda',
    '// congelado. Los textos bubble siguen apareciendo/desapareciendo por encima.',
    '(function () {',
    '  "use strict";',
    '',
    '  var FRAME_COUNT = ' + FRAME_COUNT + ';',
    '',
    '  gsap.registerPlugin(ScrollTrigger);',
    '',
    '  var lenis = new Lenis({',
    '    duration: 1.2,',
    '    easing: function (t) { return Math.min(1, 1.001 - Math.pow(2, -10 * t)); },',
    '    smoothWheel: true',
    '  });',
    '  lenis.on("scroll", ScrollTrigger.update);',
    '  gsap.ticker.add(function (time) { lenis.raf(time * 1000); });',
    '  gsap.ticker.lagSmoothing(0);',
    '',
    '  var canvas = document.getElementById("canvas");',
    '  var ctx = canvas.getContext("2d");',
    '',
    '  // ---- Anclas del nav: usar lenis.scrollTo para que quede sincronizado ----',
    '  document.querySelectorAll(\'a[href^="#"]\').forEach(function (a) {',
    '    a.addEventListener("click", function (e) {',
    '      var target = document.getElementById(a.getAttribute("href").slice(1));',
    '      if (!target) return;',
    '      e.preventDefault();',
    '      lenis.scrollTo(target, { offset: -10 });',
    '    });',
    '  });',
    '',
    '  // ---- Reveal circular del hero: se abre rapido con el primer scroll -----',
    '  var revealDistance = window.innerHeight * 0.6;',
    '  function updateReveal() {',
    '    var p = Math.min(1, Math.max(0, window.scrollY / revealDistance));',
    '    var eased = 1 - Math.pow(1 - p, 3);',
    '    canvas.style.clipPath = "circle(" + (eased * 150) + "% at 50% 50%)";',
    '  }',
    '  canvas.style.clipPath = "circle(0% at 50% 50%)";',
    '  lenis.on("scroll", updateReveal);',
    '',
    '  // ---- Precarga de frames + loader ---------------------------------------',
    '  var loader = document.getElementById("loader");',
    '  var loaderBarFill = document.getElementById("loader-bar-fill");',
    '  var loaderPercent = document.getElementById("loader-percent");',
    '  var placeholder = document.getElementById("bottle-placeholder");',
    '  var frames = [];',
    '  var currentFrame = -1;',
    '  var dpr = Math.min(window.devicePixelRatio || 1, 2);',
    '',
    '  function pathForFrame(i) {',
    '    return "assets/frames/frame_" + String(i + 1).padStart(4, "0") + ".webp";',
    '  }',
    '',
    '  function resizeCanvas() {',
    '    canvas.width = window.innerWidth * dpr;',
    '    canvas.height = window.innerHeight * dpr;',
    '    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);',
    '    revealDistance = window.innerHeight * 0.6;',
    '    updateReveal();',
    '    if (currentFrame >= 0) drawFrame(currentFrame);',
    '  }',
    '',
    '  var IMAGE_SCALE = 0.78;',
    '  var bgColor = "#1A1033";',
    '',
    '  function sampleBgColor(img) {',
    '    try {',
    '      var tmp = document.createElement("canvas");',
    '      tmp.width = 16; tmp.height = 16;',
    '      var tctx = tmp.getContext("2d");',
    '      tctx.drawImage(img, 0, 0, 16, 16);',
    '      var d = tctx.getImageData(0, 0, 16, 16).data;',
    '      var r = 0, g = 0, b = 0, n = 0;',
    '      for (var i = 0; i < 16; i++) {',
    '        [[i, 0], [i, 15], [0, i], [15, i]].forEach(function (p) {',
    '          var k = (p[1] * 16 + p[0]) * 4;',
    '          r += d[k]; g += d[k + 1]; b += d[k + 2]; n++;',
    '        });',
    '      }',
    '      r = r / n; g = g / n; b = b / n;',
    '      // A diferencia de bbanime.vercel.app (cuyo propio video ya tiene un',
    '      // fondo de estudio blanco), nuestro video tiene un fondo grisaceo;',
    '      // lo aclaramos hacia blanco para lograr el mismo resultado visual.',
    '      var WHITEN = 0.97;',
    '      r = r + (255 - r) * WHITEN;',
    '      g = g + (255 - g) * WHITEN;',
    '      b = b + (255 - b) * WHITEN;',
    '      bgColor = "rgb(" + Math.round(r) + "," + Math.round(g) + "," + Math.round(b) + ")";',
    '    } catch (e) {}',
    '  }',
    '',
    '  function drawFrame(index) {',
    '    var img = frames[index];',
    '    if (!img || !img.naturalWidth) return;',
    '    var cw = window.innerWidth, ch = window.innerHeight;',
    '    var iw = img.naturalWidth, ih = img.naturalHeight;',
    '    var scale = Math.max(cw / iw, ch / ih) * IMAGE_SCALE;',
    '    var dw = iw * scale, dh = ih * scale;',
    '    var dx = (cw - dw) / 2, dy = (ch - dh) / 2;',
    '    ctx.fillStyle = bgColor;',
    '    ctx.fillRect(0, 0, cw, ch);',
    '    ctx.filter = "saturate(1.15) brightness(1.06)";',
    '    ctx.drawImage(img, dx, dy, dw, dh);',
    '    ctx.filter = "none";',
    '  }',
    '',
    '  function initScrub() {',
    '    var track = document.getElementById("top");',
    '    ScrollTrigger.create({',
    '      trigger: track,',
    '      start: "top top",',
    '      end: "bottom bottom",',
    '      scrub: true,',
    '      onUpdate: function (self) {',
    '        var idx = Math.min(FRAME_COUNT - 1, Math.max(0, Math.floor(self.progress * FRAME_COUNT)));',
    '        if (idx !== currentFrame) {',
    '          currentFrame = idx;',
    '          drawFrame(idx);',
    '        }',
    '      }',
    '    });',
    '',
    '    // Pequeno zoom sobre la botella al llegar a la seccion final "Tu botella".',
    '    var tiendaSection = document.getElementById("tienda");',
    '    if (tiendaSection) {',
    '      ScrollTrigger.create({',
    '        trigger: tiendaSection,',
    '        start: "top 70%",',
    '        end: "top 5%",',
    '        scrub: true,',
    '        onUpdate: function (self) {',
    '          var scale = 1 + self.progress * 0.14;',
    '          canvas.style.transform = "scale(" + scale.toFixed(3) + ")";',
    '        }',
    '      });',
    '    }',
    '  }',
    '',
    '  function loadFrames() {',
    '    var loaded = 0;',
    '    var failed = 0;',
    '    for (var i = 0; i < FRAME_COUNT; i++) {',
    '      (function (idx) {',
    '        var img = new Image();',
    '        img.onload = function () {',
    '          if (idx === 0) sampleBgColor(img);',
    '          onSettled();',
    '        };',
    '        img.onerror = function () { failed++; onSettled(); };',
    '        img.src = pathForFrame(idx);',
    '        frames[idx] = img;',
    '      })(i);',
    '    }',
    '    function onSettled() {',
    '      loaded++;',
    '      var pct = Math.round((loaded / FRAME_COUNT) * 100);',
    '      loaderBarFill.style.width = pct + "%";',
    '      loaderPercent.textContent = pct + "%";',
    '      if (loaded === FRAME_COUNT) {',
    '        if (failed > FRAME_COUNT * 0.5) {',
    '          // La mayoria de los frames no cargo: nos quedamos con el placeholder.',
    '          placeholder.classList.add("visible");',
    '          loader.classList.add("hidden");',
    '          return;',
    '        }',
    '        resizeCanvas();',
    '        currentFrame = 0;',
    '        drawFrame(0);',
    '        loader.classList.add("hidden");',
    '        window.addEventListener("resize", resizeCanvas);',
    '        initScrub();',
    '      }',
    '    }',
    '  }',
    '',
    '  loadFrames();',
    '',
    '  // ---- Header: se esconde al bajar, vuelve al subir (asi no tapa la ------',
    '  // botella durante el scroll principal, pero el nav sigue disponible). -----',
    '  var header = document.getElementById("site-header");',
    '  var lastScroll = 0;',
    '  var navOpenRef = document.getElementById("nav-links");',
    '  ScrollTrigger.create({',
    '    start: "top -80",',
    '    onUpdate: function (self) {',
    '      var y = self.scroll();',
    '      header.classList.toggle("scrolled", y > 80);',
    '      var goingDown = y > lastScroll;',
    '      var navOpen = navOpenRef && navOpenRef.classList.contains("open");',
    '      if (!navOpen) {',
    '        header.classList.toggle("hidden-nav", goingDown && y > 220);',
    '      }',
    '      lastScroll = y;',
    '    }',
    '  });',
    '',
    '  // ---- Mobile nav ---------------------------------------------------------',
    '  var toggle = document.getElementById("nav-toggle");',
    '  var links = document.getElementById("nav-links");',
    '  if (toggle && links) {',
    '    toggle.addEventListener("click", function () {',
    '      var open = links.classList.toggle("open");',
    '      toggle.setAttribute("aria-expanded", open ? "true" : "false");',
    '    });',
    '    links.querySelectorAll("a").forEach(function (a) {',
    '      a.addEventListener("click", function () {',
    '        links.classList.remove("open");',
    '        toggle.setAttribute("aria-expanded", "false");',
    '      });',
    '    });',
    '  }',
    '',
    '  // ---- Los textos bubble aparecen/desaparecen al cruzar cada seccion -----',
    '  // (play/reverse por umbral, no scrub continuo: asi funciona igual de bien',
    '  // con scroll normal que con saltos de navegacion por ancla).',
    '  function scrubReveal(el, persist) {',
    '    gsap.set(el, { opacity: 0, y: 46 });',
    '    gsap.to(el, {',
    '      opacity: 1, y: 0, duration: 0.7, ease: "power2.out",',
    '      scrollTrigger: {',
    '        trigger: el,',
    '        start: "top 85%",',
    '        end: "bottom 15%",',
    '        toggleActions: persist ? "play none none none" : "play reverse play reverse"',
    '      }',
    '    });',
    '  }',
    '',
    '  document.querySelectorAll(".phase").forEach(function (section) {',
    '    var copy = section.querySelector(".phase-copy");',
    '    if (!copy) return;',
    '    scrubReveal(copy, section.dataset.persist === "true");',
    '  });',
    '',
    '  // ---- Counters ------------------------------------------------------------',
    '  document.querySelectorAll(".stat-number").forEach(function (el) {',
    '    var target = parseFloat(el.dataset.value);',
    '    var decimals = parseInt(el.dataset.decimals || "0", 10);',
    '    gsap.fromTo(el, { textContent: 0 }, {',
    '      textContent: target,',
    '      duration: 1.8,',
    '      ease: "power1.out",',
    '      snap: { textContent: decimals === 0 ? 1 : 0.01 },',
    '      scrollTrigger: { trigger: el.closest(".phase"), start: "top 70%", toggleActions: "play none none reverse" }',
    '    });',
    '  });',
    '',
    '})();',
    ''
  ].join('\n');
}

// ---------------------------------------------------------------------------
// docs/ARCHITECTURE.md
// ---------------------------------------------------------------------------
function buildArchitectureMd() {
  return [
    '# ADR-001: Arquitectura del sitio BBAnime',
    '',
    '**Status:** Accepted (ver notas de actualizacion v2, v3 y v4 abajo)',
    '**Date:** 2026-07-19',
    '**Deciders:** Cliente BBAnime, Grow Estudio Digital',
    '',
    '## Actualizacion v4 (2026-07-21)',
    '',
    'Llego el video final del cliente (`hf_20260721_192343_...mp4`, 1280x720, 24fps,',
    '~15s: botella vestida que se desviste, flota y se vuelve a vestir en loop',
    'perfecto). El cliente pidio cambiar de "loop autoplay de fondo" a **scroll-',
    'scrubbing real, estilo paginas de producto de Apple**: la posicion de scroll',
    'controla exactamente que frame se muestra, y la animacion se congela si el',
    'usuario deja de scrollear.',
    '',
    'Implementacion:',
    '',
    '- Se extrajeron **181 frames** con `ffmpeg` (`fps=12,scale=960:540`, ver',
    '  comando abajo) a `assets/frames/frame_0001.webp` ... `frame_0181.webp`.',
    '  **Se uso WebP en vez del PNG pedido originalmente**: 181 frames en PNG',
    '  (sin compresion con perdida) hubieran pesado varias decenas de MB; en WebP',
    '  calidad 80 el total quedo en ~3.55MB. Si en algun momento se necesita PNG',
    '  por algun motivo puntual, es un solo flag de ffmpeg para regenerar.',
    '- `js/app.js` precarga los 181 frames al cargar la pagina (con barra de',
    '  progreso), y un `ScrollTrigger` con `scrub: true` sobre `<main>` (de "top',
    '  top" a "bottom bottom") mapea el progreso de scroll de TODA la pagina',
    '  (0 a 1) al indice de frame correspondiente, dibujado en `<canvas>` (no',
    '  `<img>`, para que el cambio de frame sea instantaneo y sin parpadeos).',
    '- El `<video autoplay loop>` de la v3 se elimino: ya no aplica, porque ahora',
    '  el frame depende del scroll, no de un reloj interno del video.',
    '- El placeholder CSS animado de las versiones anteriores se mantiene como',
    '  **fallback de emergencia** (si mas de la mitad de los frames no llegan a',
    '  cargar), pero ya no es el camino principal.',
    '- El archivo de video original se copio a',
    '  `assets/video/bbanime-loop.mp4` (queda como fuente, no se usa directamente',
    '  en la pagina).',
    '',
    '```bash',
    'ffmpeg -y -i assets/video/bbanime-loop.mp4 -vf "fps=12,scale=960:540" \\',
    '  -c:v libwebp -quality 80 -compression_level 4 assets/frames/frame_%04d.webp',
    '```',
    '',
    '## Actualizacion v3 (2026-07-20)',
    '',
    'El cliente aclaro que la botella tenia que quedar fija de fondo en toda la web',
    '(no en un portal circular acotado). En ese momento, sin el video final todavia,',
    'se implemento como loop autoplay 100% CSS. Esto fue reemplazado en v4 por el',
    'scroll-scrubbing real descripto arriba.',
    '',
    '## Actualizacion v2 (2026-07-20)',
    '',
    'El cliente compartio capturas de un video de referencia con la direccion visual',
    'que quiere: fondo cosmico navy/violeta, tipografia bubble rosa/blanca, sparkles y',
    'stats con iconos. Se rehizo la piel visual completa (paleta, tipografia, copy,',
    'iconografia). Esta parte se mantiene sin cambios en v4.',
    '',
    '## Contexto',
    '',
    'BBAnime vende botellas termo personalizadas de anime, impresas en 3D. La landing',
    'page de una sola pagina usa el video del producto como "hero" scroll-scrubbeado',
    '(estilo Apple), con texto que aparece/desaparece por encima, y deriva el trafico',
    'a una tienda externa.',
    '',
    'Skills usadas en este proyecto: `web-rebuilder`, `frontend-design`, `seo-optimizer`,',
    '`video-to-website`, `seedance-loop-prompt`, `scroll-video`.',
    '',
    '## Decision',
    '',
    'Sitio estatico HTML5 + CSS3 + Vanilla JS (sin build step ni framework). Los 181',
    'frames viven en `.bg-scene` (`position: fixed`, detras de todo el contenido) y se',
    'dibujan en `<canvas>` segun el progreso de scroll de `<main>`. El contenido',
    '(`main`) scrollea normalmente encima, en `position: relative` con z-index mayor;',
    'cada seccion (`.phase`) aparece y desaparece con un fundido controlado por scroll',
    '(`GSAP ScrollTrigger` con `scrub: true`), sin tarjetas ni fondos propios.',
    '',
    '## Opciones consideradas',
    '',
    '### Opcion A: HTML/CSS/JS vanilla + canvas scroll-scrub (elegida)',
    '| Dimension | Evaluacion |',
    '|---|---|',
    '| Complejidad | Media (precarga de 181 imagenes + mapeo de scroll) |',
    '| Costo | Ninguno (sin dependencias de build) |',
    '| Fidelidad al pedido | Alta: es exactamente el patron de las paginas de producto de Apple |',
    '',
    '**Pros:** control total del frame mostrado, se congela al parar de scrollear,',
    'sin dependencias de reproduccion de video (autoplay policies, buffering).',
    '**Contras:** requiere precargar 181 imagenes al entrar al sitio (~3.55MB).',
    '',
    '### Opcion B: `<video>` con `currentTime` controlado por scroll',
    '| Dimension | Evaluacion |',
    '|---|---|',
    '| Complejidad | Media-alta (seeking de video no es instantaneo entre keyframes) |',
    '| Fidelidad al pedido | Media: puede tener micro-lag/parpadeos al saltar entre frames, que es',
    'exactamente lo que el cliente pidio evitar ("sin parpadeos") |',
    '',
    '**Motivo del descarte:** buscar (`seek`) un `<video>` cuadro a cuadro via scroll',
    'no es instantaneo (el navegador tiene que decodificar hasta el keyframe mas',
    'cercano), lo que genera el parpadeo que el cliente explicitamente pidio evitar.',
    'El canvas con imagenes precargadas dibuja cada frame de forma instantanea.',
    '',
    '## Consequences',
    '',
    '- El peso inicial de carga subio en ~3.55MB (los 181 frames WebP). Aceptable para',
    '  una landing de marca con un loader visible durante la precarga.',
    '- Si el cliente manda un video nuevo, hay que volver a correr el comando ffmpeg de',
    '  arriba (o ajustar `fps`/`scale` si el peso final no convence) y actualizar',
    '  `FRAME_COUNT` en `scaffold.js` si la cantidad de frames cambia.',
    '- El link a la tienda externa y el dominio final son placeholders que hay que',
    '  reemplazar.',
    '',
    '## Action items',
    '',
    '1. [x] Cliente entrego el video final y se extrajeron los 181 frames',
    '2. [ ] Reemplazar la URL placeholder de la tienda externa (nav + seccion `#tienda`)',
    '3. [ ] Reemplazar dominio placeholder (`bbanime.vercel.app`) por el dominio final en',
    '       meta tags, canonical, sitemap.xml y robots.txt',
    '4. [ ] Reemplazar links de Instagram/TikTok/email placeholder por los reales',
    '5. [ ] Deploy: `npx vercel --prod`',
    ''
  ].join('\n');
}

// ---------------------------------------------------------------------------
// README.md
// ---------------------------------------------------------------------------
function buildReadmeMd() {
  return [
    '# BBAnime — sitio web',
    '',
    'Landing page de una sola pagina para BBAnime, botellas termo personalizadas de anime',
    'impresas en 3D. El hero es un scroll-scrubbing real (estilo paginas de producto de',
    'Apple): la posicion de scroll controla exactamente que frame de la botella se',
    'muestra, y los textos bubble aparecen/desaparecen por encima. HTML5 + CSS3 +',
    'Vanilla JS, sin build step.',
    '',
    'Generado con la skill `engineering:architecture` combinando `web-rebuilder`,',
    '`frontend-design`, `seo-optimizer`, `video-to-website`, `seedance-loop-prompt` y',
    '`scroll-video`. El ADR completo esta en [docs/ARCHITECTURE.md](docs/ARCHITECTURE.md)',
    '(incluye las notas de actualizacion v2, v3 y v4 con los cambios de direccion).',
    '',
    '## Estructura',
    '',
    '```',
    'webbotella/',
    '  index.html',
    '  css/style.css',
    '  js/app.js',
    '  assets/video/bbanime-loop.mp4   (video original del cliente, no se usa en la pagina)',
    '  assets/frames/frame_0001.webp   (181 frames extraidos, los usa el canvas)',
    '  ...frame_0181.webp',
    '  docs/ARCHITECTURE.md',
    '  docs/SEEDANCE-PROMPT.md',
    '  robots.txt',
    '  sitemap.xml',
    '  scaffold.js                     (script que genero todo esto)',
    '```',
    '',
    '## Ver el sitio en local',
    '',
    '```bash',
    'npx serve .',
    '```',
    '',
    'o',
    '',
    '```bash',
    'python -m http.server 8000',
    '```',
    '',
    '## Como funciona el scroll-scrubbing',
    '',
    '`js/app.js` precarga los 181 frames (`assets/frames/frame_0001.webp` a',
    '`frame_0181.webp`) con una barra de progreso. Una vez cargados, un',
    '`ScrollTrigger` (`scrub: true`) mide el progreso de scroll de TODA la pagina',
    '(desde el top de `<main>` hasta su final, justo antes del footer) y dibuja el',
    'frame correspondiente en `<canvas>`. Como el scroll va de 0 a 1 a lo largo de',
    'toda la web, la botella queda vestida en el hero (frame 0), se desviste durante',
    '"Qué hacemos" / "Tu universo" / "Proceso" / "Datos", y vuelve a quedar vestida',
    'justo en la seccion final de compra (frame 180) — el mismo loop perfecto del',
    'video, ahora controlado por el usuario en vez de reproducirse solo.',
    '',
    'Si el usuario deja de scrollear, el frame queda congelado ahi (no hay reloj ni',
    'autoplay corriendo de fondo).',
    '',
    '## Si llega un video nuevo (re-generar los frames)',
    '',
    '1. Copiar el archivo a `assets/video/bbanime-loop.mp4` (pisa el anterior).',
    '2. Borrar los frames viejos y re-extraer:',
    '   ```bash',
    '   rm assets/frames/frame_*.webp',
    '   ffmpeg -y -i assets/video/bbanime-loop.mp4 -vf "fps=12,scale=960:540" \\',
    '     -c:v libwebp -quality 80 -compression_level 4 assets/frames/frame_%04d.webp',
    '   ```',
    '3. Contar cuantos frames se generaron (`ls assets/frames | wc -l`) y, si el',
    '   numero cambio, actualizar `FRAME_COUNT` en `scaffold.js` (arriba del todo) y',
    '   volver a correr `node scaffold.js` para que `js/app.js` quede sincronizado.',
    '',
    'Si el video nuevo dura mucho mas o menos que ~15s, `fps=12` puede dar muchos mas',
    'o menos frames — ajustar ese numero para mantener el peso total razonable (una',
    'buena referencia es apuntar a 150-200 frames en total).',
    '',
    '## Pendientes antes de publicar',
    '',
    '- [ ] Reemplazar `https://tu-tienda-externa.com` en `index.html` (nav y seccion',
    '      `#tienda`) por la URL real de la tienda.',
    '- [ ] Reemplazar el dominio placeholder `bbanime.vercel.app` (meta tags, canonical,',
    '      `sitemap.xml`, `robots.txt`) por el dominio final.',
    '- [ ] Reemplazar links de Instagram/TikTok/email placeholder por los reales.',
    '- [ ] Agregar imagen real para `og:image` / `twitter:image` (hoy apunta a',
    '      `assets/img/og-image.jpg`, que todavia no existe).',
    '',
    '## Deploy',
    '',
    '```bash',
    'npx vercel --prod',
    '```',
    ''
  ].join('\n');
}

// ---------------------------------------------------------------------------
// robots.txt / sitemap.xml (sin cambios de contenido)
// ---------------------------------------------------------------------------
function buildRobotsTxt() {
  return [
    'User-agent: *',
    'Allow: /',
    'Sitemap: https://bbanime.vercel.app/sitemap.xml',
    ''
  ].join('\n');
}

function buildSitemapXml() {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- TODO: actualizar dominio cuando este definido -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    '  <url>',
    '    <loc>https://bbanime.vercel.app/</loc>',
    '    <lastmod>2026-07-21</lastmod>',
    '    <changefreq>monthly</changefreq>',
    '    <priority>1.0</priority>',
    '  </url>',
    '</urlset>',
    ''
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Ejecutar (no vuelve a generar docs/SEEDANCE-PROMPT.md: ya cumplio su proposito
// y el video real ya existe; se deja intacto como referencia historica).
// ---------------------------------------------------------------------------
console.log('Generando sitio BBAnime (v4, scroll-scrubbing real con', FRAME_COUNT, 'frames) en:', ROOT);
write('index.html', [buildIndexHtml()]);
write('css/style.css', [buildStyleCss()]);
write('js/app.js', [buildAppJs()]);
write('docs/ARCHITECTURE.md', [buildArchitectureMd()]);
write('README.md', [buildReadmeMd()]);
write('robots.txt', [buildRobotsTxt()]);
write('sitemap.xml', [buildSitemapXml()]);
fs.mkdirSync(path.join(ROOT, 'assets', 'img'), { recursive: true });
console.log('Listo.');
